### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by dh9yap** [sa2blv/SVXportal#1]
Too bad that it is not for non-Linux experts to install.

Otherwise, the Idde is excellent

My Server Ubuntu LTS 18 

It starts with the installation of these packages.
sudo apt-get install libapache2-mod-php7.0 php7.0 php7.0-common php7.0-curl php7.0-dev php7.0-gd php-pear php-imagick php7.0-mcrypt php7.0-mysql php7.0-ps php7.0-xsl

73 dh9yap Jürgen

**Comment by sa2blv** [comment]
trying to fix an installation file for the prodject install.php.
that makes it mutch easyer to install

**Comment by dh9yap** [comment]
Hi Peter :-)
I have created the database MYSQL with the install.php and exported it into the sql directory.
The config.php adapted.
But how is the SVXefelector connected?
My svxreflector runs on port 5300 with the IP 213.202.228.66
here my svxreflector.conf
[GLOBAL]
#CFG_DIR=svxreflector.d
TIMESTAMP_FORMAT="%d.%m.%Y %H:%M:%S"
LISTEN_PORT=5300
SQL_TIMEOUT=300
SQL_TIMEOUT_BLOCKTIME=3600
CODECS=OPUS
TG_FOR_V1_CLIENTS=1
RANDOM_QSY_RANGE=12399:100
HTTP_SRV_PORT=8080
And my config.php

- <?php
$host = "localhost";
$user ="root";
$password ="#########";
$db="svx";

$link =  mysqli_connect($host, $user, $password , $db);
// Site name
$sitename = "2.1";

// Live link
$livelink="http://213.202.228.66:8000";

// Svx recording folder
$dir="/var/www/svx/svxrecording";

// svxreflektor server adress;
$serveradress ="http://213.202.228.66:5300/";
?>

here the public address:
http://213.202.228.66/test/SVXportal/
73 DH9yap Jürgen

**Comment by dh9yap** [comment]
And my config.php
<?php
$host = "localhost";
$user ="root";
$password ="#########";
$db="svx";

$link =  mysqli_connect($host, $user, $password , $db);
// Site name
$sitename = "2.1";

// Live link
$livelink="http://213.202.228.66:8000";

// Svx recording folder
$dir="/var/www/svx/svxrecording";

// svxreflektor server adress;
$serveradress ="http://213.202.228.66:5300/";
?>
here the public address:
http://213.202.228.66/test/SVXportal/
73 DH9yap Jürgen

**Comment by sa2blv** [comment]
change 
 $serveradress ="http://213.202.228.66:5300/";
to 
 $serveradress ="http://213.202.228.66:8080/status";

**Comment by sa2blv** [comment]
added the missing file svx_stat.js change the adress as  mentiond abowe and add the new file it shoud work

**Comment by sa2blv** [comment]
Added some code fixes to get  rid of the charater problems

**Comment by dh9yap** [comment]
Hi Peter
Thank you for your very fast handling of my problem.
After you have adapted the source code it works.
Now I have my gateways in the monitor and the audio stream works too.
Only no audio files are stored.
Use ----> Darkice, Icecast2
Audio format mp3
Do you have a solution approach?


73 Jürgen DH9YAP
