### ISSUE TITLE
Info nodes on map

### ISSUE THREAD

**Issue by stefano-lattanzio** [sa2blv/SVXportal#10]
I wish know how show stations on map within svxportal. Is it possibile that nodes have to writes json code in own node_info.json file?? Which parameters is necessary to add? Where can I find infos for this issue? Thnaks in advance.

**Comment by sa2blv** [comment]
the format shoud be a numeric float  and on type 'EPSG:4326', 'EPSG:3857'
"lat": 63.858458,
"long": 20.32261,
