### ISSUE TITLE
Request..

### ISSUE THREAD

**Issue by ur3qjw** [sa2blv/SVXportal#11]
Hello Peter,
Found several lines without translation: "Back", "Filter:", "CSV index", "time", "Search".
Please add the wiki directory on github, With the Swedish leadership:
konfiguration_foer_sysops.html
svxreflector.html
Also a sample file: node_info.json For Simplex and Repeater versions.
The log page is not scaled to the screen size :( Search fields go beyond it.
In the database: "repeater", "users". Here, need something to write?
Image in the archive.
[Image.tar.gz](https://github.com/sa2blv/SVXportal/files/4582972/Image.tar.gz)

**Comment by sa2blv** [comment]
i have fix most of the languge issuse as you discribed i will comit all to update 2.3. 
have some smaler fixes to do before 

// Peter

**Comment by ur3qjw** [comment]
Thank you so much!
I will wait for the update.
And then I will send localization corrections.

**Comment by ur3qjw** [comment]
Hello Peter!
Please see online streaming on SVXportal.
QSO Monitor - Listen Live.
I set up and noticed ...
If listening from the site, then it will fully load the system at 100%.
This is normal? 100% system load when listening. Can I somehow optimize it?
Regards, Volodymyr

**Comment by sa2blv** [comment]
> 
> 
> Hello Peter!
> Please see online streaming on SVXportal.
> QSO Monitor - Listen Live.
> I set up and noticed ...
> If listening from the site, then it will fully load the system at 100%.
> This is normal? 100% system load when listening. Can I somehow optimize it?
> Regards, Volodymyr

i have made several optimizations for listen live and the databse the is included in the 2.3 update i will se if i can commit to git this weakend. i have to add a system for updating mysql/ maria db.

**Comment by ur3qjw** [comment]
Hello Peter!
Does it make sense to change some points a bit?
To make it more clear what they are responsible for:
"Name" => "Talkgroup Name"
"Time" => "Local Time"
"TG" => "TG#"

Regards, Volodymyr

**Comment by UR3QJW** [comment]
Hello Peter!
Please update the Ukrainian translation.
Also, it seems: "Receivers => Filter:" - no translation support
Regards, Volodymyr. "UA SvxReflector Team"
[SVXportal-uk_UA.tar.gz](https://github.com/sa2blv/SVXportal/files/4639355/SVXportal-uk_UA.tar.gz)

**Comment by sa2blv** [comment]
i have added the translation to the pot file and to the system 
here you can dowload the latest pot file
https://svxportal.sm2ampr.net/locale/svxportal.pot

**Comment by ur3qjw** [comment]
Hello Peter!
Thanks, I updated. Found a few more:
"QSO Monitor" - "undefined".
"Log" - "Reciver", "Node".
"Admin" - "Sign In", "LOGIN"
"Map" - "true"
And perhaps it’s worth adding “%” to the signal level in the log:
"Reciver SK2GJ is active signal level 8%"
I did not translate everything. I look forward to the release.
[SVXportal-uk_UA.tar.gz](https://github.com/sa2blv/SVXportal/files/4640325/SVXportal-uk_UA.tar.gz)

**Comment by sa2blv** [comment]
![bild](https://user-images.githubusercontent.com/10690071/82163500-ef4f4280-98ab-11ea-951d-97459d9ed5a4.png)
here is the new admin interface for the portal

**Comment by ur3qjw** [comment]
It is very cool!

**Comment by ur3qjw** [comment]
Hello Peter!
When can we expect the release of the SVXportal v.2.3?
Please update the localization files: [SVXportal-uk_UA.tar.gz](https://github.com/sa2blv/SVXportal/files/4659389/SVXportal-uk_UA.tar.gz)
Regards, Volodymyr

**Comment by sa2blv** [comment]
i have made some testing during the week i nead to fix an db update scipt. if all works well i think i will publish this weekend

**Comment by sa2blv** [comment]
It is out check this

https://github.com/sa2blv/SVXportal/wiki/Update--or-install-2.3

**Comment by ur3qjw** [comment]
Hi Peter!
I can not login to admin.php
Reflector clients - no list of stations.
The flag of Norway is large.
![1](https://user-images.githubusercontent.com/16563084/82728364-7bbc9380-9cf8-11ea-9baa-b61857e71a6a.png)
Poedit, says that there are errors in the file: "svxportal.pot"

**Comment by sa2blv** [comment]
seams to be a database problem can you send me a copy ?
i will fix the icon sems to be a file transfer issue.
i will reupload the pot file later 

// Peter

**Comment by ur3qjw** [comment]
which files do you need?

**Comment by sa2blv** [comment]
can i get an tempory login to your phpmyadmin 
to check the db ?

**Comment by UR3QJW** [comment]
> can i get an tempory login to your phpmyadmin
> to check the db ?

I wrote to the mail

**Comment by iu0krr** [comment]
Hello Peter,

I am installing the new version of your dashboard on a second server, which database should I set up for a new installation of the four that are in the sql folder ??

Thanks

**Comment by sa2blv** [comment]
if you are installing a new system use svx.sql 
if you ara upgrading from 2.2 use update2-3.sql

**Comment by sa2blv** [comment]
> 
> 
> > can i get an tempory login to your phpmyadmin
> > to check the db ?
> 
> I wrote to the mail

seams to be a timout problem in the data base upgrade scipt.
i fixed your db,

**Comment by iu0krr** [comment]
> if you are installing a new system use svx.sql
> if you ara upgrading from 2.2 use update2-3.sql

Thanks Peter, but i have another questions for you!

![image](https://user-images.githubusercontent.com/64253243/82761819-975d9200-9dfd-11ea-858a-a5912ff6c93d.png)

I have problems with the logs, on the screen I have this error, it refers to line 80 of the logdemon.php file, then even if he writes that he was able to make the query, in the database there is nothing in the log table

**Comment by sa2blv** [comment]
> 
> 
> > if you are installing a new system use svx.sql
> > if you ara upgrading from 2.2 use update2-3.sql
> 
> Thanks Peter, but i have another questions for you!
> 
> ![image](https://user-images.githubusercontent.com/64253243/82761819-975d9200-9dfd-11ea-858a-a5912ff6c93d.png)
> 
> I have problems with the logs, on the screen I have this error, it refers to line 80 of the logdemon.php file, then even if he writes that he was able to make the query, in the database there is nothing in the log table

it not a problem just a missing data in the json icommit a fix for it, try :)

//Peter

**Comment by iu0krr** [comment]
> > > if you are installing a new system use svx.sql
> > > if you ara upgrading from 2.2 use update2-3.sql
> > 
> > 
> > Thanks Peter, but i have another questions for you!
> > ![image](https://user-images.githubusercontent.com/64253243/82761819-975d9200-9dfd-11ea-858a-a5912ff6c93d.png)
> > I have problems with the logs, on the screen I have this error, it refers to line 80 of the logdemon.php file, then even if he writes that he was able to make the query, in the database there is nothing in the log table
> 
> it not a problem just a missing data in the json icommit a fix for it, try :)
> 
> //Peter

Hello peter!!
http://svxlink.iw6ocm.it/SVXportal/index.php

I tried to change the logdeamon.php file with your new version, but I have the same error, tell me where am I wrong please ?!

**Comment by sa2blv** [comment]
> I tried to change the logdeamon.php file with your new version, but I have the same error, tell me where am I wrong please ?!

i think this is a case of php neads to ignor a value if not exsitst
added a new file that have value ignore. if not exist 


// Peter

**Comment by iu0krr** [comment]
Hello Peter!!

First of all, I hope you are fine !!

I wanted to ask you, why does the receiver table change constantly, I mean that there are moments that many receivers are not displayed ?? !!

**Comment by sa2blv** [comment]
![bild](https://user-images.githubusercontent.com/10690071/98449540-b85c3a00-2134-11eb-8b2b-ebe28148b727.png)
this table ?

**Comment by iu0krr** [comment]
NO, this http://svxportal.iu0krr.it/SVXportal/list_reciver.php

**Comment by sa2blv** [comment]
added som handlers in code  the the page tabel dosent update all information continusly. but whe it is nessesary to update the table row
