### ISSUE TITLE
Show remote rx/tx on the map. future request.

### ISSUE THREAD

**Issue by iw0red** [sa2blv/SVXportal#12]
Hi Peter, is it possible to add in the json file the gps informations of the remote receivers to make possible to see them on the map?
73 Marco IW0RED.

**Comment by sa2blv** [comment]
this feature exist we jave some remote recivers on the map. you nead to  add a secound qth to the qth array in the json and asign a Letter to the RX_ID=T to the coresponding reciver in svxlink.conf or if remote trx remotetrx.conf.

to show recivers on the map select Show Receivers in Actions

// Peter


 {
      "name": "Ersobda",
      "pos": {
        "lat": 63.858458,
        "long": 20.32261,
        "loc": "kp03cu"
      },
      "rx": {
        "T": {
          "name": "Ersboda",
          "freq": 432.725,
          "sqlType": "CTCSS",
          "ant": [
            {
              "comment": "KOT antenn",
              "height": 10
            }
          ]
        }
      }

    }

![bild](https://user-images.githubusercontent.com/10690071/81301886-ef646c80-9079-11ea-89b3-f42126331280.png)

**Comment by iw0red** [comment]
Fine thanks. 
I'm going to try it.
73 Marco IW0RED.

**Comment by DF2HS** [comment]
I have a question.

The receiver of the repeater e.g. DB0HHH has RX ID =1 in svxlink.conf. I edited the config of the remote receiver to RX ID = T, but the remote receiver is not shown in the map. The remote receiver is located at DF0HHH.

I also wrote this values in the node_info.json file.

You may have a look at http://44.149.84.9:8000/index.php

The whole setup is not complete, yet.

What am I doing wrong?

73
Sandy DF2HS

**Comment by sa2blv** [comment]
cant reach url

**Comment by DF2HS** [comment]
You can try this URL:
http://portal.rag-hh.de/

I am experiencing some errors with editing the info pages, too. Images can not be saved everytime, as there occus an error "cannot convert blob ... to blob" sometimes.

The page for DB0HHH contains images linked from qrz.com which I manually created with phpmyadmin and an online html editor. My Test Page contains a image which I uploaded with the tinyMCE editor, but I am not able to add a second image or more text to that page.

The whole page is not beeing translated into german. When I visit your page everything gets translated.

Remote receivers are not displayed in the map.

73
Sandy DF2HS

**Comment by DF2HS** [comment]
The best option for support would be if you could get access to hamnet, maybe through VPN?

**Comment by DF2HS** [comment]
The Svxportal is not working behind a proxy, while it does at the same time when I open it via hamnet. Something is going wrong, I believe.

So this is DB0HHH repeater with it´s two receivers:

![Screenshot 2022-02-21 085956](https://user-images.githubusercontent.com/68467281/154912605-cdbb28d3-f1dc-485a-aad9-411dfd75c7ca.png)

When I press PTT on my handheld radio you can see the receivers are receiving and the signal levels are displayed;
![Screenshot 2022-02-21 091218](https://user-images.githubusercontent.com/68467281/154914203-747599c3-8198-4344-a9f4-e886bc9dc2f3.png)

This is how it looks when I click on the repeater symbol in the map:
![Screenshot 2022-02-21 090310](https://user-images.githubusercontent.com/68467281/154912958-ad782c3a-8dff-4c7d-8343-4c2b1b90f374.png)

The remote receiver should be displayed at the location DF0HHH, but there I only can see the 70cm repeater DF0HHH. The 2m remote receiver for DB0HHH is not displayed.

![Screenshot 2022-02-21 090428](https://user-images.githubusercontent.com/68467281/154913182-49ce48f8-73a7-4d89-9639-e51e895dd166.png)

This is the code from node_info.json for DB0HHH:

[node_info.json.txt](https://github.com/sa2blv/SVXportal/files/8107394/node_info.json.txt)


Do you see any errors?

73
Sandy DF2HS

**Comment by sa2blv** [comment]
This is a problen o reciveres. the system expect a float value not a string.
thy this patch 
[index.zip](https://github.com/sa2blv/SVXportal/files/8137058/index.zip)

// Peter

**Comment by DF2HS** [comment]
Seems to work, but what exactly is the problem? Is it the name of the stations or the rx id? Frequency written as 145.750 instead of 145,750 ?

Thanks

**Comment by sa2blv** [comment]
The cordinate is in string not as float,
wat he problem whats the freqvensy problem look the same

**Comment by DF2HS** [comment]
hmm.. I created the node_info.json file using your tool. maybe there is something wrong I guess.
