### ISSUE TITLE
Schade

### ISSUE THREAD

**Issue by dh9yap** [sa2blv/SVXportal#19]
Too complicated to install!
An installation script would help a lot.
73 Jürgen
Here is my link:
http://213.202.228.66/mm/SVXportal/index.php
Registering and logging in does not work.
No statistics!
Also no map visible.

73 Jürgen

**Comment by sa2blv** [comment]
yo havent added a database to config.php. 
Have you try to run install.php in your browser ?

**Comment by sa2blv** [comment]
if you want you can use the anselbe scipt from svx https://github.com/sm0svx/ansible-svxlink

**Comment by dh9yap** [comment]
Hi there
I reinstalled everything.
first edited the config.php and then executed install.php.
now the menus all work, but i can't see any clients.
I call http://213.202.228:8081/status
the log is just not displayed in svxportal.

var/www/html/SVXportal/config.php
--------------------------------------------------------------------------------------------------------

> <?php
$host = "localhost";
$user ="svxportal";
$password ="XXXXXXXXXXXXX";
$db="svxportal";

$link =  mysqli_connect($host, $user, $password , $db);
// Site name
$sitename = "2.2";

// Live link
$livelink="http://213.202.228.66:8000/stream";

// Svx recording folder
$dir="/var/www/svxrecording";

// svxreflektor server adress;
$serveradress ="http://213.202.228.66/SVXportal/reflektor%20proxy/";
#$serveradress ="http://213.202.228.66:8081/status";
// login form recording
//$use_logein= true;
// Iframe under system description
//$iframe_documentation_url  ="http://sk3w.se/dokuwiki/doku.php?id=svxreflector&do=export_xhtml";

// Default Position
$default_lat ="62.676160";
$default_long ="17.633479";
$default_zoom =5;

// default tg player
//$default_tg_player = 240;

// Default date
//$start_date_defined ="2020-01-12";

// Mysql_Reflektor
$reflektor_db = 1 ;

$reflektor_db_host =            "127.0.0.1";
$reflektor_db_user =    "";
$reflektor_db_password =        "";
$reflektor_db_db =              "";


$use_mqtt=False;
$mqtt_host = "";
$mqtt_port = "";
$mqtt_TLS = "";

-----------------------------------------------------------------------------------------------------------------
73 jürgen

my Svxportalsite http://213.202.228.66/SVXportal/index.php

**Comment by sa2blv** [comment]
change this value in config.php
$serveradress ="http://213.202.228.66/SVXportal/reflektor%20proxy/";
to 
$serveradress ="http://213.202.228.66/SVXportal/reflector_proxy/";

**Comment by dh9yap** [comment]
Hi Peter
Thank you for your prompt reply.
You're doing a very good job ... great project.
Your proposed change works!
Now I have to look at the statistics. It won't show up to me.

73 Jürgen

**Comment by sa2blv** [comment]
check that the crontab scipt is working with screen -x or if run as root sudo screen -x

**Comment by dh9yap** [comment]
Alle 20,0s: php station_heartbeat.php                                                                                       v293571: Sun Dec 27 17:13:27 2020

sh: 0: getcwd() failed: No such file or directory
Could not open input file: station_heartbeat.php

**Comment by sa2blv** [comment]
4. add this line to your corntab

@reboot sleep 60 && screen  -d -m bash -c  'cd /var/www/ ; watch -n 1  php logdeamon.php;'
@reboot sleep 60 && screen  -d -m bash -c  'cd /var/www/ ; watch -n 20  php station_heartbeat.php;'


please note that the folder /var/www/ shall be your instalation folder.

5. reboot or manualy start 

screen  -d -m bash -c  'cd /var/www/ ; watch -n 20  php station_heartbeat.php;'
screen  -d -m bash -c  'cd /var/www/ ; watch -n 1  php logdeamon.php;'


**check your location /var/www/  is corrent**

**Comment by dh9yap** [comment]
i gave a wrong path in the crontab
let's see if it works now

**Comment by dh9yap** [comment]
Alle 20,0s: php station_heartbeat.php                                                                                       v293571: Sun Dec 27 17:25:56 2020

check data to write!PHP Warning:  fopen(tmp/cache_json.txt): failed to open stream: No such file or directory in /var/www/html/SVXportal/station_heartbeat.ph
p on line 141
PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/SVXportal/station_heartbeat.php on line 142
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/html/SVXportal/station_heartbeat.php on line 143

**Comment by sa2blv** [comment]
seams to be okay this is just a cache warning

**Comment by dh9yap** [comment]
it does not work ...
but now take a break. I will get back to you later
