### ISSUE TITLE
Logs - Connection Failed

### ISSUE THREAD

**Issue by W4JEW** [sa2blv/SVXportal#20]
Hello,

I just installed SVXportal on a Raspberry Pi running svxlink. Whenever I go to access the Log page from the tree on the left side of the page, I get the message "Connection failed: Access denied for user 'svx'@'localhost' (using password:YES).

The username for the MySQL (MariaDB) database on my system is Svxportal and that is the username I provided when I ran install.php. Once install.php finished, I received a message that it completed successfully. I'm not sure where username 'svx' is coming from.

**Comment by sa2blv** [comment]
Sems to be an error in config.php

it shoud loock loke this 


$host = "localhost";
$user ="Svxportal ";
$password ="Secretpassword";
$db="Svxportal";

$link =  mysqli_connect($host, $user, $password , $db);
// Site name
$sitename = "2.2";

// Live link
$livelink="http://svxportal.sm2ampr.net:8000/svxcard96";

// Svx recording folder
$dir="/var/www/svxrecording";
 
// svxreflektor server adress;
$serveradress ="http://sk3w.se/svxreflektor/reflektor%20proxy/";

// login form recording
//$use_logein= true;
// Iframe under system description
//$iframe_documentation_url  ="http://sk3w.se/dokuwiki/doku.php?id=svxreflector&do=export_xhtml";

// Default Position
$default_lat ="62.676160";
$default_long ="17.633479";
$default_zoom =5;

// default tg player
//$default_tg_player = 240;

// Default date
//$start_date_defined ="2020-01-12";

// Mysql_Reflektor
$reflektor_db = 1 ;

$reflektor_db_host =	 	"127.0.0.1";
$reflektor_db_user = 	"";
$reflektor_db_password = 	"";
$reflektor_db_db = 		"";


$use_mqtt=False;
$mqtt_host = "";
$mqtt_port = "";
$mqtt_TLS = "";
