### ISSUE TITLE
Testing Beta 2.5

### ISSUE THREAD

**Issue by gcm70** [sa2blv/SVXportal#22]
Hi,
is it possible to download and test version 2.5 Beta?.
DTMF and node commands implemented in this version?
73

**Comment by sa2blv** [comment]
Hi.
the releses of version 2.5 i soon to arive , i will upload in the nermast weeks. 
just have som final testning to do . the dtmf is implemented in this version .

**Comment by sa2blv** [comment]
Release canidate is out  for testing
