### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by GabeHC** [sa2blv/SVXportal#24]
I follow instruction to setup on a P4 and P3A+, there are no candidate for MySQL but MariaDB instead.
create database with no problem, when create user there are syntax error
and when run install.php all I got is this

> Connect failed: Access denied for user ''@'localhost' (using password: YES)

please help. Thanks

**Comment by sa2blv** [comment]
Hello.
we are still workong on some bugs.
but if you find this helpfull i think this is an databas issue chek this manual ,
for help

https://www.granudden.info/Ham/Repeatrar/Dokument/SvxPortal2.5.pdf


// Peter
