### ISSUE TITLE
Colors and name Talkgroup

### ISSUE THREAD

**Issue by iz2bks** [sa2blv/SVXportal#26]
In my dashboard the name and color part of the Talkgroups are not populated, is there any particular setting?
http://ref-iq2aq.dmrbrescia.it/

**Comment by sa2blv** [comment]
You need to change the colors in the admin interface.

check this page under admin interface

https://granudden.info/Ham/Repeatrar/Dokument/SvxPortal2.5.pdf


Den mån 17 jan. 2022 kl 09:02 skrev iz2bks ***@***.***>:

**Comment by iz2bks** [comment]
Admin interface
Click the Admin interface button.

Where do I find the interface button?

**Comment by sa2blv** [comment]
http://ref-iq2aq.dmrbrescia.it/admin.php

Den mån 17 jan. 2022 kl 13:42 skrev iz2bks ***@***.***>:

**Comment by iz2bks** [comment]
All right, congratulations, you did a spectacular job, thank you
