### ISSUE TITLE
Errors in the code that may affect development

### ISSUE THREAD

**Issue by f5vmr** [sa2blv/SVXportal#29]
I have spent a great deal of time viewing the project in learning about PHP, jscript and HTML. In using VSCode I discovered two problems that may have escaped the authors eye. In some pages, a variable 'i' was missing the '$' ahead of it to make it '$i' in the relevant loop structure. Because of the way VSCode works I cannot tell you in which files the error existed. However one error that I can confirm, I found in the index.html in the kml folder.  A closing ')' brace was missing from the jscript. I think I found the correct place in which to add this brace, but it may affect the production of Version 2.6 if it is not corrected.

 Understanding the personal difficulties of the author, I have made a complete correction of all the spelling errors in a repository on my own github/f5vmr.

A great project - looking forward to 2.6

**Comment by sa2blv** [comment]
file and line ?

**Comment by sa2blv** [comment]
file 
[SVXportal](https://github.com/sa2blv/SVXportal)/[kml](https://github.com/sa2blv/SVXportal/tree/master/kml)/index.php /
the files kml is oboslite and not int use anymore.

**Comment by sa2blv** [comment]
variable 'i' and $i is mixe in the code due to mix between javascipt  and php.

**Comment by f5vmr** [comment]
I have been using VSCode in several projects, increasing my back office skill in PHP. Because VSCode batch-corrects errors I didn’t note any line number.

Initial examination of 2.5 by VSCode reported several repeating issues - undeclared variable ‘i’ in a number of places where most of the loop shows variable '$i’. 

The variable $i is in several files - get_statistics.php, index.php, log.php, request_notification.php, user_settings.php admin/log.php admin/settings.php admin get_statistics.php and possibly some other files.

The missing brace ')' is  in xml/index.php but where it went I wasn’t sure. There were a couple of other errors reported in the same file, but this is probably due to the missing brace.

There are also a number of CSS errors reported by VSCode that empty rulesets - ' style=“” ' should not be used.

Hope that helps


Chris

**Comment by f5vmr** [comment]
All understood, Thanks for the clarification.

Chris

**Comment by f5vmr** [comment]
Closed
