### ISSUE TITLE
Last heard Station

### ISSUE THREAD

**Issue by dhartmann1979** [sa2blv/SVXportal#30]
Hi,
first thanks for the great work. When will the new Release come out? The Last Heard Station is a wunderful feature that we need ;)  And the State of: https://svxportal.sm2ampr.net/ would be nice ;)

**Comment by sa2blv** [comment]
The beta release will come out as soon as i fixed the database update scripts.

// BLV

**Comment by sa2blv** [comment]
the beta test relese is out know! :)
