### ISSUE TITLE
Bosnian language

### ISSUE THREAD

**Issue by e77eh** [sa2blv/SVXportal#33]
Hi Peter,

First of all, thank you for the SVXPortal design, it is very interesting and useful. I installed the portal with my radio amateur friends from E7 and it is currently on the link: http://e7link.dtdns.org:49485

I used language corrections and translated the portal into Bosnian language, so please add Bosnian language to the portal.

Thank you.

73 de E77EH
[bs_BA.zip](https://github.com/sa2blv/SVXportal/files/13238531/bs_BA.zip)

**Comment by sa2blv** [comment]
added to languge core for portal 2.6 :)

**Comment by e77eh** [comment]
Thank`s.
