### ISSUE TITLE
Map doesn't work

### ISSUE THREAD

**Issue by dh9yap** [sa2blv/SVXportal#34]
Hello
I got the current svxportal via git clone.
Was able to install everything. Only the map remains empty.
Here is my address: http://svxlink.ddnss.de
I'd be happy for help.
73 Jürgen DH9YAP

**Comment by dh9yap** [comment]
There are other things that don't work, but first get the map to work

**Comment by sa2blv** [comment]
the code stops generateing php from here
	<?php if (detect_empty_cache_table () == true ){?>



	 const myTimeout = setTimeout(get_station_chat_year, 450);


	<?php }?>

is the  **trafic_day_statistics** table in your database ?

**Comment by sa2blv** [comment]
Found the problem try run https://github.com/sa2blv/SVXportal/blob/master/sql/update2.6.sql
manually in phpmyadmin. you are missing some datebase tables.

// SA2BLV Peter

**Comment by dh9yap** [comment]
Hello Peter
thank you for the quick response. But I still don't see a map.
I see the following message in the console:
![portal](https://github.com/sa2blv/SVXportal/assets/19761696/f40b6117-0a7f-490a-87c0-2055c22fef7d)

**Comment by sa2blv** [comment]
try run php file in **console with php index.php** and the you will get the error message. 
the problem is that the code stope excuting when generating the map part of the page.

**Comment by dh9yap** [comment]
Hi Peter
This is displayed in index.php in the console
![portal2](https://github.com/sa2blv/SVXportal/assets/19761696/fbd7db3c-82cf-47ad-8aa6-183bbdb20eed)

**Comment by dh9yap** [comment]
Maybe a setting in the php.ini is necessary?

**Comment by sa2blv** [comment]
the problem in not in php.ini. it's is somthing wrong with the mysql database. 
the code stops to execute. before generate the map code. try run in terminal in your www folder.
ex /var/www/html **run "php index.php "** there you will get an error message.

**Comment by dh9yap** [comment]
Hallo Peter :-)
here is the output:

        PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'svxportal.trafic_day_statistics' doesn't exist in /var/www/html/function.php:458
Stack trace:
#0 /var/www/html/function.php(458): mysqli->query()
#1 /var/www/html/index.php(3698): detect_empty_cache_table()
#2 {main}
  thrown in /var/www/html/function.php on line 458
root@ubuntu:/var/www/html#

**Comment by sa2blv** [comment]
have yo added this lines to your mysql database? 
https://github.com/sa2blv/SVXportal/blob/master/sql/update2.6.sql
as previously posted ? 

you can do it using php my admin

**Comment by dh9yap** [comment]
update2.6.sql
I imported it!!!!
I installed it on another server http://212.132.119.189/ Now it works, but the login doesn't work. I probably still have to use php-mcrypt
install. Which cannot be installed via apt-get. I would like to provide instructions to make it work. I'm using Ubuntu 22.04 Jammy Apache2 php8

**Comment by sa2blv** [comment]
Try run **php login.php** in terminal. can be somthing missing

**Comment by dh9yap** [comment]
root@ubuntu:/var/www/html# php login.php
PHP Warning:  Undefined array key "login" in /var/www/html/login.php on line 4
PHP Warning:  Undefined array key "password" in /var/www/html/login.php on line 5
PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown column 'image_url' in 'field list' in /var/www/html/login.php:13
Stack trace:
#0 /var/www/html/login.php(13): mysqli_query()
#1 {main}
  thrown in /var/www/html/login.php on line 13

**Comment by dh9yap** [comment]
Had problems with install.php. I imported the SQL file with phpmyadmin. Do all SQL files have to be imported and if so, in what order
73
![sql](https://github.com/sa2blv/SVXportal/assets/19761696/4adda5fd-37c2-4cb9-ab07-82860e1092f9)

**Comment by sa2blv** [comment]
it seams to be a missing field. 
i nead to check the update file
try 

ALTER TABLE users
ADD image_url varchar(255); if it fix the problem

**Comment by sa2blv** [comment]
you can add this as well 
ALTER TABLE users
ADD Reset_token varchar(99);

**Comment by dh9yap** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Database Modification</title>
</head>
<body>

<h2>MySQL Database Modification</h2>

<ol>
  <li>Open the terminal on your computer.</li>
  <li>Type the following command and press Enter:</li>
</ol>

<code>mysql -u root -p</code>

<p>This command connects you to the MySQL database using the username "root". You'll be prompted to enter your password.</p>

<ol start="3">
  <li>Enter your password and press Enter. Your password won't be displayed for security reasons while you type it.</li>
  <li>After successfully logging into MySQL, you need to select your specific database where you want to make changes. To do this, use the <code>USE</code> command followed by the name of your database. For example:</li>
</ol>

<code>USE your_database;</code>

<p>Replace "your_database" with the actual name of your database.</p>

<ol start="5">
  <li>Now you can make the desired changes to your table. For example, add a new column <code>image_url</code>. To do this, type the following command and press Enter:</li>
</ol>

<code>ALTER TABLE users ADD image_url varchar(255);</code>

<ol start="6">
  <li>Next, you can add another column, for example <code>Reset_token</code>, by entering the following command and pressing Enter:</li>
</ol>

<code>ALTER TABLE users ADD Reset_token varchar(99);</code>

<p>After completing these steps, the specified changes should have been successfully made to your database. You can exit MySQL using the <code>exit</code> command or by closing the terminal window.</p>

</body>
</html>
`

**Comment by dh9yap** [comment]
Thank you Peter :-) It works!!
The map and the login.
we can close the request.
73 de Jürgen
