### ISSUE TITLE
Rename "reflektor proxy" subdirectory

### ISSUE THREAD

**Issue by sm0svx** [sa2blv/SVXportal#8]
What do you say about renaming the "reflektor proxy" subdirectory to something better?  It is awkward so have spaces in URL:s and the word "reflector" is misspelled. Maybe just "proxy" or "reflector_proxy"?

**Comment by sa2blv** [comment]
im going to look on that to the upload of 2.2 code

**Comment by sa2blv** [comment]
Fix for 2.2 relese
