### ISSUE TITLE
Correct setting

### ISSUE THREAD

**Issue by ur3qjw** [sa2blv/SVXportal#9]
Hello!
Tell me how to correctly bind SVXportal to SvxReflector?
This is absolutely not clear:
> add adress to svxrefector proxy to config.php
> edit the $url parameter in the reflektorproxy/index.php director to match the  SVXreflector server.

Show an example please.

**Comment by iw0red** [comment]
Hi,
in svxreflector.conf 
--- HTTP_SRV_PORT=8181
in config.php
--- $serveradress ="http://iw0.red:8181/status"; (server address:port)
I can't find $url parameter in the reflektorproxy/index.php

73 Marco IW0RED.

**Comment by sa2blv** [comment]
// MYSQL / mariadb
$host = "127.0.0.1";
$user ="svxpotal";
$password ="";
$db="svx";

$link =  mysqli_connect($host, $user, $password , $db);
// Site name
$sitename = "2.2";

// Live link
$livelink="http://svxportal.sm2ampr.net:8000/svxcard96";

// Svx recording folder
$dir="/var/www/svx/svxrecording";

// svxreflektor server adress;
$serveradress ="https://svxportal.sm2ampr.net/reflector_proxy/";

// login form recording
//$use_logein= true;
// Iframe under system description
//$iframe_documentation_url  ="http://sk3w.se/dokuwiki/doku.php?id=svxreflector&do=export_xhtml";

// Default Position
$default_lat ="62.676160";
$default_long ="17.633479";




Here is my config.php for svxportal i removed private parts like database

config inside reflector_proxy


$Svx_reflector_address = ""http://reflektorserver:8181/status"; "


if you want to use the statistics module in 2.2 you nead to run 
@reboot sleep 60 && screen  -d -m bash -c  'cd /var/www/svx/ ; watch -n 1  php logdeamon.php;'
in crontab. the requierments for this is screen  


// Peter

**Comment by ur3qjw** [comment]
2.2 - Is this another version?
2.1 is indicated here:
$sitename = "2.1";
https://github.com/sa2blv/SVXportal/blob/master/config.php

**Comment by ur3qjw** [comment]
Sorry, but it doesn’t work.... :(((
There are data:
http://svx.*****.org.ua:****/status
Not Work:
// svxreflektor server adress;
$serveradress ="http://svx.******.org.ua/reflector_proxy/";

$Svx_reflector_address = ""http://svx.******.org.ua:status"; "

**Comment by sa2blv** [comment]
> 
> 
> Sorry, but it doesn’t work.... :(((
> There are data:
> http://svx.*****.org.ua:****/status
> Not Work:
> // svxreflektor server adress;
> $serveradress ="http://svx.******.org.ua/reflector_proxy/";
> 
> $Svx_reflector_address = ""http://svx.******.org.ua:status"; "

try this see that the string was not  correct 
$Svx_reflector_address = "http://reflektorserver:8181/status ";

**Comment by ur3qjw** [comment]
Now works!
Many thanks Peter, your edits helped!

**Comment by iw0red** [comment]
Hi, it works more or less. I can't see the signal level and other details.
Thanks,
Marco IW0RED.

**Comment by sa2blv** [comment]
you nead to add id to rx in svxlink.conf
RX_ID=B to your recivers and asign the coresponding letter to the json 

here is an example of the node_info.json

{
  "NodeLocation": "Dummy repeater name",
  "hidden": false,
  "toneToTalkgroup": {
        "107.2":24022,
        "118.8":2406,
        "123":2400,
        "141.3":2403,
        "151.4":2404,
        "91.5":2405,
        "146.2":2402,
        "156.7":2407,
        "136.5":0,
        "88.5":240
},
  "qth": [
    {
      "name": "vannas",
      "pos": {
        "lat": 63.844387,
        "long": 19.824023,
        "loc": "kp03cu",
        "sysop":"SM2RIX / SA2BLV"
      },
        "sysop":"SM2RIX / SA2BLV",
      "rx": {
        "A": {
          "name": "Granlundsberget",
          "freq": 432.725,
          "sqlType": "COR",
          "ctcssFreq": [107.2, 67.0, 77.0, 127.3],
          "ant": [
            {
              "comment": "4 stack",
              "height": 310,
              "dir": 180
            }
          ]
        }
      },
      "tx": {
        "G": {
          "name": "TX1",
          "freq": 434.725,
          "pwr": 20,
          "ctcssFreq": [107.2],
          "ant": [
            {
              "comment": "Yagi south",
              "height": 50,
              "dir": 180
            },
            {
              "comment": "Yagi north",
              "height": 50,
              "dir": 0
            }
          ]
        }
      }
    },
          {
      "name": "Ersobda",
      "pos": {
        "lat": 63.858458,
        "long": 20.32261,
        "loc": "kp03cu"
      },
      "rx": {
        "T": {
          "name": "Ersboda",
          "freq": 432.725,
          "sqlType": "CTCSS",
          "ant": [
            {
              "comment": "KOT antenn",
              "height": 10
            }
          ]
        }
      }

    },
                  {
      "name": "Böleäng",
      "pos": {
        "lat": 63.821621,
        "long": 20.220049,
        "loc": "kp03cu"
      },
        "sysop":"SM2RIX / SA2BLV",
      "rx": {
        "B": {
          "name": "Böläng",
          "freq": 432.725,
          "sqlType": "CTCSS",
          "ant": [
            {
              "comment": "KOT antenn",
              "height": 10
            }
          ]
        }
      }

    }




  ]
}

**Comment by iw0red** [comment]
Thanks Peter, I'm going to do more test.
73 Marco IW0RED.

**Comment by ur3qjw** [comment]
Hello Peter,
Where to look for files for:
1. "_System description"
2. "konfiguration_foer_sysops"
3. "Talkgroups"
4. ">_Log"
How to configure them?

**Comment by ur3qjw** [comment]
How to slightly increase the scale of the map? (click "Zoom in")

**Comment by iu0krr** [comment]
Hello Peter,
I have a problem in the map menu and in the CTSS list menu, they are completely empty, do you have any idea why it doesn't work and where am I wrong?

Thanks, IU0KRR

**Comment by sa2blv** [comment]
> 
> 
> Hello Peter,
> I have a problem in the map menu and in the CTSS list menu, they are completely empty, do you have any idea why it doesn't work and where am I wrong?
> 
> Thanks, IU0KRR

You nead to add this to the local  node_info.json file  on eatch node 

wher first column is tone and the other is talkgroup 

"toneToTalkgroup": {
"107.2":24022,
"118.8":2406,
"123":2400,
"141.3":2403,
"151.4":2404,
"91.5":2405,
"146.2":2402,
"156.7":2407,
"136.5":0,
"88.5":240
},

**Comment by sa2blv** [comment]
> 
> 
> Hello Peter,
> Where to look for files for:
> 
>     1. "_System description"
> 
>     2. "konfiguration_foer_sysops"
> 
>     3. "Talkgroups"
> 
>     4. ">_Log"
>        How to configure them?

System description our way to configur this att he moment 
is to use the text file called echolink.txt or by using an html page stored on the server.
to use the html page edit and uncomment this line in the config.php
 //$iframe_documentation_url ="http://sk3w.se/dokuwiki/doku.php?id=svxreflector&do=export_xhtml";

"Talkgroups"

are stored in the database 
and 
">_Log" is showing the last 500 entrys in the database from the log deamon.
i have future plans to optimize the log and add an simple admin interface 

// Peter DE SA2BLV

**Comment by sa2blv** [comment]
> 
> 
> How to slightly increase the scale of the map? (click "Zoom in")

Hello i commited an new index file and added this parameter 
to config
$default_zoom =5; 
this will allow you to sett the zoom on the default possiostion on map 

// Peter

**Comment by UR3QJW** [comment]
SvxLink, does not transmit the entire geolocation?
QTH Name","pos":{"lat":47,"loc":"KN88MT","long":35}
How to get the level of signal transmission? It is not displayed.

**Comment by ur3qjw** [comment]
> > How to slightly increase the scale of the map? (click "Zoom in")
> 
> Hello i commited an new index file and added this parameter
> to config
> $default_zoom =5;
> this will allow you to sett the zoom on the default possiostion on map
> 
> // Peter

It works! Thanks!

**Comment by ur3qjw** [comment]
> > Hello Peter,
> > Where to look for files for:
> > ```
> > 1. "_System description"
> > 
> > 2. "konfiguration_foer_sysops"
> > 
> > 3. "Talkgroups"
> > 
> > 4. ">_Log"
> >    How to configure them?
> > ```
> 
> System description our way to configur this att he moment
> is to use the text file called echolink.txt or by using an html page stored on the server.
> to use the html page edit and uncomment this line in the config.php
> //$iframe_documentation_url ="http://sk3w.se/dokuwiki/doku.php?id=svxreflector&do=export_xhtml";
> 
> "Talkgroups"
> 
> are stored in the database
> and
> ">_Log" is showing the last 500 entrys in the database from the log deamon.
> i have future plans to optimize the log and add an simple admin interface
> 
> // Peter DE SA2BLV

Peter,
Perhaps on GIT create a folder, "wiki" ?..
And copy your file: "svxreflector.html"
And maybe several versions: "node_info.json"
For duplex repeater and simplex node. Please.

**Comment by iu0krr** [comment]
> > Hello Peter,
> > I have a problem in the map menu and in the CTSS list menu, they are completely empty, do you have any idea why it doesn't work and where am I wrong?
> > Thanks, IU0KRR
> 
> You nead to add this to the local node_info.json file on eatch node
> 
> wher first column is tone and the other is talkgroup
> 
> "toneToTalkgroup": {
> "107.2":24022,
> "118.8":2406,
> "123":2400,
> "141.3":2403,
> "151.4":2404,
> "91.5":2405,
> "146.2":2402,
> "156.7":2407,
> "136.5":0,
> "88.5":240
> },

Thanks Peter, now work fine!!!

**Comment by iu0krr** [comment]
Hello Peter,
We have a problem due, we think, to the svxlink versions, not all of our repeaters have version 2.0, for this reason we have noticed that the bridge map does not update, if we try to disconnect the nodes with version 1.0, it works perfectly.
In your opinion, is it possible to make some changes to also display the nodes with the old version of svxlink ??

Thanks, 73 IU0KRR, REDNET Team !!!

**Comment by sa2blv** [comment]
>  We have a problem due, we think, to the svxlink versions, not all of our repeaters have version 2.0, for this reason we have noticed that the bridge map does not update, if we try to disconnect the nodes with version 1.0, it works perfectly.

I hav commitetd a patch to the portal that handels string in the long and lat positions 
i tested it on your portal an it seams to work

**Comment by iu0krr** [comment]
Thanks Peter, we have updated and everything is working properly.
We remain on contact for future updates.

Thanks

**Comment by ur3qjw** [comment]
Hello Peter,
Please add Ukrainian localization for SVXportal. Thanks!
Regards, Volodymyr. "UA SvxReflector Team"
[uk_UA.tar.gz](https://github.com/sa2blv/SVXportal/files/4536648/uk_UA.tar.gz)

**Comment by sa2blv** [comment]
> 
> 
> Hello Peter,
> Please add Ukrainian localization for SVXportal. Thanks!
> Regards, Volodymyr. "UA SvxReflector Team"
> [uk_UA.tar.gz](https://github.com/sa2blv/SVXportal/files/4536648/uk_UA.tar.gz)

thanks i added to repo and portal. 
i saw i missed to add some text. so i updated the pot file

// Peter SA2BLV

**Comment by sa2blv** [comment]
> 
> 
> Thanks Peter, we have updated and everything is working properly.
> We remain on contact for future updates.
> 
> Thanks

is it possible to get an Italian localization file ?

**Comment by iu0krr** [comment]
> > Thanks Peter, we have updated and everything is working properly.
> > We remain on contact for future updates.
> > Thanks
> 
> is it possible to get an Italian localization file ?

Yes why not, I try to work on it right away!!

**Comment by iu0krr** [comment]
> > Thanks Peter, we have updated and everything is working properly.
> > We remain on contact for future updates.
> > Thanks
> 
> is it possible to get an Italian localization file ?

Yes why not, I try to work on it right away!!

**Comment by iu0krr** [comment]
Peter can you replace menu reciver with receiver and CTSS with CTCSS??

**Comment by UR3QJW** [comment]
> > Hello Peter,
> > Please add Ukrainian localization for SVXportal. Thanks!
> > Regards, Volodymyr. "UA SvxReflector Team"
> > [uk_UA.tar.gz](https://github.com/sa2blv/SVXportal/files/4536648/uk_UA.tar.gz)
> 
> thanks i added to repo and portal.
> i saw i missed to add some text. so i updated the pot file
> 
> // Peter SA2BLV

Hello Peter,
I will update and recheck the localization and send you later.
Look please:
http://svx.greenwave.org.ua/123/
http://svx.greenwave.org.ua:8383/status
I can’t understand why it doesn’t work?
I am using Ubuntu 20.04. Can there be a problem in compatibility with php?
Localization does not work.
Talkgroups - no.
Color CTCSS - no.
Signal strength - no.
The exact position on the map. SvxLink, does not transmit the entire geolocation?
QTH Name","pos":{"lat":47,"loc":"KN88MT","long":35}

**Comment by sa2blv** [comment]
> 
> 
> > > Hello Peter,
> > > Please add Ukrainian localization for SVXportal. Thanks!
> > > Regards, Volodymyr. "UA SvxReflector Team"
> > > [uk_UA.tar.gz](https://github.com/sa2blv/SVXportal/files/4536648/uk_UA.tar.gz)
> > 
> > 
> > thanks i added to repo and portal.
> > i saw i missed to add some text. so i updated the pot file
> > // Peter SA2BLV
> 
> Hello Peter,
> I will update and recheck the localization and send you later.
> Look please:
> http://svx.greenwave.org.ua/123/
> http://svx.greenwave.org.ua
> http://svx.greenwave.org.ua:8383/status
> I can’t understand why it doesn’t work?
> I am using Ubuntu 20.04. Can there be a problem in compatibility with php?
> Localization does not work.
> Talkgroups - no.
> Color CTCSS - no.
> Signal strength - no.
> The exact position on the map. SvxLink, does not transmit the entire geolocation?
> QTH Name","pos":{"lat":47,"loc":"KN88MT","long":35}

run this on your server sudo locale-gen uk_UA

**Comment by sa2blv** [comment]
sudo locale-gen uk_UA
sudo locale-gen sv_SE
sudo locale-gen nb_NO

**Comment by sa2blv** [comment]
> 
> 
> Peter can you replace menu reciver with receiver and CTSS with CTCSS??

i have commited and push  fix for the wrong spelling

**Comment by sa2blv** [comment]
> 
> 
> > > > Hello Peter,
> > > > Please add Ukrainian localization for SVXportal. Thanks!
> > > > Regards, Volodymyr. "UA SvxReflector Team"
> > > > [uk_UA.tar.gz](https://github.com/sa2blv/SVXportal/files/4536648/uk_UA.tar.gz)
> > > 
> > > 
> > > thanks i added to repo and portal.
> > > i saw i missed to add some text. so i updated the pot file
> > > // Peter SA2BLV
> > 
> > 
> > Hello Peter,
> > I will update and recheck the localization and send you later.
> > Look please:
> > http://svx.greenwave.org.ua/123/
> > http://svx.greenwave.org.ua
> > http://svx.greenwave.org.ua:8383/status
> > I can’t understand why it doesn’t work?
> > I am using Ubuntu 20.04. Can there be a problem in compatibility with php?
> > Localization does not work.
> > Talkgroups - no.
> > Color CTCSS - no.
> > Signal strength - no.
> > The exact position on the map. SvxLink, does not transmit the entire geolocation?
> > QTH Name","pos":{"lat":47,"loc":"KN88MT","long":35}
> 

> > Talkgroups - no.
for talkgroups you nead to add them to the database "Talkgroup" i use phpmyadmin
at the moment. the plan is to add an admin page
int table RefletorStations you can add color to the stations
this table is automatic filled by the robot script.

 Signal strength - no.
requiers that you have declared RX_ID=B on the reciver in svxlink.conf
on eatch node and added
the same letter to the node_info.json

"rx": {
    "B": {
      "name": "Böläng",
      "freq": 432.725,
      "sqlType": "CTCSS",
      "ant": [
        {
          "comment": "KOT antenn",
          "height": 10
        }
      ]
    }


 The exact position on the map. SvxLink, does not transmit the entire geolocation?
what kind of delimiter are you using?

my positions are lokink like this
20.32261
you can use string as well "20.32261"
in the node_info.json

**Comment by UR3QJW** [comment]
> sudo locale-gen uk_UA
> sudo locale-gen sv_SE
> sudo locale-gen nb_NO

System localization: uk_UA.UTF-8
When was generated: uk_UA.KOI8-U
Then it helped.

**Comment by iu0krr** [comment]
Peter, please, first to upload on GIT. check it.
[uk_IT.zip](https://github.com/sa2blv/SVXportal/files/4539666/uk_IT.zip)

**Comment by iu0krr** [comment]
Peter i find a mistake, in statistic  "Most used reciver"

Thanks !!!

**Comment by sa2blv** [comment]
> 
> 
> Peter i find a mistake, in statistic "Most used reciver"
> 
> Thanks !!!

I have uploaded the italy languge to git

if you use ubunt you may nead to run this commands 

    sudo apt-get install gettext
    sudo locale-gen uk_UA
    sudo locale-gen sv_SE
    sudo locale-gen nb_NO
    sudo locale-gen it_IT

// Peter

**Comment by iu0krr** [comment]
> > Peter i find a mistake, in statistic "Most used reciver"
> > Thanks !!!
> 
> I have uploaded the italy languge to git
> 
> if you use ubunt you may nead to run this commands
> 
> ```
> sudo apt-get install gettext
> sudo locale-gen uk_UA
> sudo locale-gen sv_SE
> sudo locale-gen nb_NO
> sudo locale-gen it_IT
> ```
> 
> // Peter

Thanks Peter !!!!!! 73 IU0KRR -> REDNET Team

**Comment by UR3QJW** [comment]
Hello Peter,
Why there is no list: "Talkgroups"? And, no colors "Talkgroups"? 
What is it:
> SELECT sum(UNIX_TIMESTAMP(`Time`)), `Talkgroup` FROM RefletorNodeLOG WHERE `Type` = '1' AND `Active` ='1' AND `Time` BETWEEN ' 00:00:00.000000' AND ' 23:59:00.000000' group by `Talkgroup`

**Comment by ur3qjw** [comment]
Hello Peter,
As it turned out, switching to another language does not work on Windows OS.
Under Linux, it works.
Regards, Volodymyr.

**Comment by sa2blv** [comment]
> 
> Under Linux, it works.

I have only tested on linux but i shall see if i can patch it to work for windows as well
